### ISSUE TITLE
SD().explicit initialization throws exception

### ISSUE THREAD

**Issue by razvan-ciochina** [jamores/eth-scapy-someip#2]
Hi,

On Python 2.7.15 there's a problem with the initialization of the explicit variable at class level which causes a throw. Removing "explicit = 1" from the class makes everything work again.

https://github.com/jamores/eth-scapy-someip/blob/4bc8224d5c5b02bee8731e8ce79c03a08db353bf/eth_scapy_someip/eth_scapy_sd.py#L246

**Comment by geynis** [comment]
Which scapy version did you used?
I have created a fix for the explicit var problem that is not related to python version but to the scapy version.
See:
https://github.com/jamores/eth-scapy-someip/pull/1

**Comment by jamores** [comment]
Sorry for my time away. I'll try today to merge back genyis request and see if that solves the problem.

**Comment by razvan-ciochina** [comment]
Hi and thank you for the quick response. I am using scapy 2.4.0

**Comment by geynis** [comment]
Hi razvan-ciochina, please see the requirements.txt file. The supported version in this project is scapy 2.3.2, after the merge of my PR you'll be able to run it with scapy 2.4.0

**Comment by jamores** [comment]
Tested with scapy 2.4 after merging @geynis changes. Version increased to 0.1.11

Thanks everyone!
