### ISSUE TITLE
Issue in parsing SOME/IP-SD packet sniffed packet

### ISSUE THREAD

**Issue by alappatakhil** [jamores/eth-scapy-someip#6]
Hi  
    I am trying to sniff  SOME/IP-SD packet send from ex_02_sd.py
    But when we print the summary of the packet, SOME/IP header is parsed but SD is displayed as raw.
   As per my understanding SD is bonded  with SOME/IP and SOME/IP with UDP. so when packet is sniffed scapy should parse both SOME/IP and SD packet.

**Comment by Murmele** [comment]
@alappatakhil did you find a solution for this problem?

**Comment by geynis** [comment]
Did you use python3? because it is still unsupported by this code.

**Comment by alappatakhil** [comment]
No our plan changed so we stopped working on it

**Comment by jamores** [comment]
Hi,
When executing example collection SD traffic is properly displayed using WireShark v3.2.3
