### ISSUE TITLE
ModuleNotFoundError: No module named 'eth_scapy_sd'

### ISSUE THREAD

**Issue by deepakreddy63** [jamores/eth-scapy-someip#8]
Hi,
I installed  eth_scapy_someip using setup.py, I try to import the commands in python to verify them and get below error. What am I doing wrong?

>>> from eth_scapy_someip import eth_scapy_someip as someip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maen/Downloads/eth-scapy-someip-master/eth_scapy_someip/__init__.py", line 2, in <module>
    import eth_scapy_sd
ModuleNotFoundError: No module named 'eth_scapy_sd'

I looked in folder and all files are present.

**Comment by jamores** [comment]
Could you please elaborate a little bit on the steps leading to your problem?
If you just clone the repo and execute 'tox', does it work?

**Comment by deepakreddy63** [comment]
Hi,

Thanks for getting back early. I could now run with py2.7 but having issues with py3.6. I get the module not found error in py3.6 env.

I tried tox now. Below is the output.

examples run-test: commands[0] | sudo /home/maen/Downloads/eth-scapy-someip-master/.tox/examples/bin/python ./examples/examples_main.py
[sudo] password for maen: 
Traceback (most recent call last):
  File "./examples/examples_main.py", line 4, in <module>
    from ex_01_someip import ex_01_someip
  File "/home/maen/Downloads/eth-scapy-someip-master/examples/ex_01_someip.py", line 5, in <module>
    from eth_scapy_someip import eth_scapy_someip as someip
  File "/home/maen/Downloads/eth-scapy-someip-master/.tox/examples/lib/python3.6/site-packages/eth_scapy_someip/__init__.py", line 2, in <module>
    import eth_scapy_sd
ModuleNotFoundError: No module named 'eth_scapy_sd'
ERROR: InvocationError for command /usr/bin/sudo .tox/examples/bin/python ./examples/examples_main.py (exited with code 1)
___________________________________________________ summary ___________________________________________________
  clean: commands succeeded
  py27: commands succeeded
  stats: commands succeeded
ERROR:   examples: commands failed

**Comment by deepakreddy63** [comment]
Hi Jamores,

Could you please update a two examples of client and server communicating via service request response like in genivi https://github.com/GENIVI/vsomeip/tree/master/examples . If not can you point out where I can find more information as it is difficult to get a full example.

Thanks

**Comment by jamores** [comment]
Hi, please check new version (0.3.0), there should be no import errors.
Take as reference how example collection import and use eth_scapy_someip modules.

Regards
